name: Build and deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: build
        run: |
          zip -r site.zip site/

      - name: prepare deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            sudo rm -rf *

      - name: upload zip
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: '${{ secrets.SSH_USER }}'
            server: '${{ secrets.SSH_IP }}'
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            local_path: './site.zip'
            remote_path: '${{ secrets.WEBSITE }}'
            sftpArgs: '-o ConnectTimeout=5'
            password: '${{ secrets.SSH_PASSWORD }}'

      - name: deploy 
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.WEBSITE }}
            unzip site.zip
            cd site
            mv {*,.[^.]*,..?*} ../ -f
            cd ../
            rm -rf site/
            rm -rf site.zip